name: dctkit
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh
  - hyperfine
  - jax
  - jaxopt
  - numpy
  - pygmo
  # - petsc4py
  - python
  - python-gmsh
  - scipy
  - typeguard
  - yaml
  - jupyterlab
  - trame
  - ipywidgets
  - pyvista
  - pip
  - pip:
    - pygmsh