name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - ampl-mp=3.1.0
  - aom=3.5.0
  - appdirs=1.4.4
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - atk-1.0=2.38.0
  - attr=2.5.1
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.0.7
  - cryptography=39.0.1
  - curl=7.88.0
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - double-conversion=3.2.0
  - eigen=3.4.0
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - fltk=1.3.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freeimage=3.18.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gmsh=4.11.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - graphviz=6.0.2
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.33
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icecream=2.1.3
  - icu=70.1
  - idna=3.4
  - imath=3.1.6
  - importlib-metadata=6.3.0
  - importlib_metadata=6.3.0
  - ipopt=3.14.11
  - ipykernel=6.22.0
  - ipyparallel=8.5.1
  - ipython=8.12.0
  - jack=1.9.22
  - jax=0.4.1
  - jaxlib=0.4.1
  - jaxopt=0.5.5
  - jedi=0.18.2
  - joblib=1.2.0
  - jpeg=9e
  - jsoncpp=1.9.5
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=7.88.0
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgd=2.3.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libglu=9.0.0
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libgrpc=1.51.1
  - libhwloc=2.9.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.9.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.21.12
  - libraw=0.21.1
  - librsvg=2.54.4
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libva=2.17.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - loguru=0.6.0
  - lz4-c=1.9.4
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - metis=5.1.0
  - mpg123=1.31.2
  - mpire=2.6.0
  - multidict=6.0.4
  - mumps-include=5.2.1
  - mumps-seq=5.2.1
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=3.0
  - nlohmann_json=3.11.2
  - nlopt=2.7.1
  - nspr=4.35
  - nss=3.88
  - numpy=1.24.2
  - occt=7.7.1
  - openexr=3.1.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.0
  - opt_einsum=3.3.0
  - p11-kit=0.24.1
  - packaging=23.1
  - pagmo=2.19.0
  - pango=1.50.12
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - ply=3.11
  - pooch=1.6.0
  - proj=9.1.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.11.4
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycparser=2.21
  - pygments=2.14.0
  - pygmo=2.19.5
  - pygraphviz=1.10
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-gmsh=4.11.1
  - python_abi=3.11
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.8
  - rapidjson=1.1.0
  - re2=2023.02.01
  - readline=8.1.2
  - requests=2.28.2
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - scotch=6.0.9
  - setuptools=67.3.2
  - sip=6.7.7
  - six=1.16.0
  - sqlite=3.40.0
  - stack_data=0.6.2
  - svt-av1=1.4.1
  - tbb=2021.7.0
  - tbb-devel=2021.7.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unixodbc=2.3.10
  - urllib3=1.26.14
  - utfcpp=3.2.3
  - vtk=9.2.5
  - wcwidth=0.2.6
  - wheel=0.38.4
  - wslink=1.10.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxmu=1.1.3
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - cachetools==5.3.0
    - chardet==5.1.0
    - distlib==0.3.6
    - filelock==3.12.0
    - platformdirs==3.3.0
    - pluggy==1.0.0
    - pyproject-api==1.5.1
    - tox==4.5.0
    - typeguard==4.0.0rc4
    - virtualenv==20.22.0
