# add dependencies from setup.cfg
name: readthedocs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pygmo
  - importlib-metadata
  - numpy
  - scipy
  - jax<=0.4.3
  - jaxlib<=0.4.3
  - gmsh
  - matplotlib
  - jaxopt
  - typing_extensions
  - typeguard
  - pip:
    - sphinx_rtd_theme
    - myst-parser[linkify]
    - sphinx>=3.2.1