# copy from environment.yaml in project root
name: readthedocs
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh
  - jax==0.5.0
  - jaxopt
  - numpy
  - pygmo
  # - petsc4py
  - python
  - python-gmsh
  - scipy
  - typeguard
  - yaml
  - pyvista
  - pip:
    - sphinx_rtd_theme
    - myst-parser[linkify]
    - sphinx>=3.2.1
    - pygmsh